#  Q. Write a program to input eight numbers from the user and display all the unique numbers (once).
s = set()

a = input("Enter number: ")
s.add(int(a))
a = input("Enter number: ")
s.add(int(a))
a = input("Enter number: ")
s.add(int(a))
a = input("Enter number: ")
s.add(int(a))
a = input("Enter number: ")
s.add(int(a))
a = input("Enter number: ")
s.add(int(a))
a = input("Enter number: ")
s.add(int(a))
a = input("Enter number: ")
s.add(int(a))

print(s)